export function black(inputStr: any): string;
export function red(inputStr: any): string;
export function green(inputStr: any): string;
export function yellow(inputStr: any): string;
export function blue(inputStr: any): string;
export function magenta(inputStr: any): string;
export function cyan(inputStr: any): string;
export function white(inputStr: any): string;
export function gray(inputStr: any): string;
export function bgBlack(inputStr: any): string;
export function bgRed(inputStr: any): string;
export function bgGreen(inputStr: any): string;
export function bgYellow(inputStr: any): string;
export function bgBlue(inputStr: any): string;
export function bgMagenta(inputStr: any): string;
export function bgCyan(inputStr: any): string;
export function bgWhite(inputStr: any): string;
export function bgGray(inputStr: any): string;
declare const _default: {};
export default _default;
